language: node_js
node_js:
- '8'
notifications:
  email: false
services:
  - redis-server
addons:
  mariadb: '10.2'
script:
 - mysql -u root -e "CREATE DATABASE IF NOT EXISTS `jsdelivr-stats-test`"
 - npm test
